In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from transformers import (
    BertTokenizer,
    BertForMaskedLM,
    BertConfig,
    LineByLineTextDataset,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
import torch
from sklearn.model_selection import train_test_split
from typing import Literal
from torch import nn
from transformers import BertModel,AutoModel
from huggingface_hub import hf_hub_download
from typing import Literal
import json

In [ ]:
import torch
from transformers import pipeline

pipeline = pipeline(task="text-generation", model="openai-community/gpt2", torch_dtype=torch.float16, device=0)
pipeline("Hello, I'm a language model")

In [ ]:
nbs = pd.read_csv('/Users/ritikrmohapatra/Documents/GitHub/Multi-Model-Bias-Detection-and-Debiasing-the-News/EDA/No_Corrupted_NBS.csv')

In [ ]:
 pip install -q -U google-genai

In [ ]:
nbs.isna().sum()

In [ ]:
nbs.head()

In [ ]:
nbs.shape[0]

In [ ]:
nbs['multimodal_label_y'].value_counts()

In [ ]:
import random

index = random.randint(1, 2185)
print(index)

In [ ]:
import requests

In [ ]:
nbs['mac_image_path'].head()

Random Selection

In [ ]:
image_path = nbs['mac_image_path'][index]
image_caption = nbs['content'][index]
article = nbs['headline'][index]
with open(image_path, 'rb') as f:
    image_bytes = f.read()

In [ ]:
image_path

In [ ]:

biased_headlin = nbs[nbs['multimodal_label_y'] == 'Likely']['headline']
Non_biased_headlin = nbs[nbs['multimodal_label_y'] == 'Unlikely']['headline']

rand_idx_1 = random.randint(0, len(biased_headlin)-1)
rand_idx_2 = random.randint(0, len(Non_biased_headlin)-1)
rand_idx_3 = random.randint(0, len(Non_biased_headlin)-1)
rand_idx_4 = random.randint(0, len(biased_headlin)-1)

In [ ]:
#https://huggingface.co/docs/transformers/main/en/generation_strategies


exam_sig = f"""
Uniased: " {Non_biased_headlin.iloc[rand_idx_2]} "
Biased: "{biased_headlin.iloc[rand_idx_1]} " """ 

exam_multi = f"""
Unbiased: "{Non_biased_headlin.iloc[rand_idx_2]}"
Biased: "{biased_headlin.iloc[rand_idx_4]}"

Unbiased: "{Non_biased_headlin.iloc[rand_idx_3]}"
Biased: "{biased_headlin.iloc[rand_idx_1]}"
"""

def build_prompt(prompt_type=str):
    if prompt_type == "zero":
        print(article)
        return f"""
Article: {article}

Rewrite the article and caption in a neutral and unbiased tone.
"""
    elif prompt_type == "single":
        print(article)

        return f"""
Article: {article}

Here is an example of debiasing:
{exam_sig}

Now, rewrite the article and caption above in a neutral and unbiased tone.
"""
    elif prompt_type == "multi":
        print(article)
        return f"""
Article: {article}

Here are examples of rewriting biased text into neutral form:
{exam_multi}

Now rewrite the article and caption above in the same neutral style.
"""
    elif prompt_type == "role":
        print(article)
        return f"""You are a professional news editor who is neutral in every scenario.Your task is to remove emotionally charged or biased language and rewrite the following article and caption in a strictly neutral,unbiased and factual tone.

Article: {article}
"""
    else:
        raise ValueError("Invalid prompt_type")

In [ ]:
!pip install google.generativeai

Gemini

In [ ]:
!pip install generativeai
!pip install google

In [ ]:
#https://ai.google.dev/gemini-api/docs/multimodal
import google.generativeai as genai


def gemini_lm(prompt_type):
    prompt = build_prompt(prompt_type)
    import google.generativeai as genai
    genai.configure(api_key="AIzaSyDNH9TmB1bzdcJGO3yI931Js7W2HJsA5Y4")

    model = genai.GenerativeModel(model_name="gemini-1.5-flash")
    response = model.generate_content(prompt)
    return response.text

gpt 2

In [ ]:
#https://huggingface.co/gpt2
from transformers import GPT2Tokenizer, GPT2LMHeadModel


tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")


tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.eos_token_id

def run_gpt2(prompt_type):
    prompt = build_prompt(prompt_type)
    inputs = tokenizer(prompt, return_tensors="pt",truncation=True,
        max_length=1024,
        padding="max_length" )
    output = model.generate(**inputs, max_new_tokens=512)
    return tokenizer.decode(output[0], skip_special_tokens=True)

In [ ]:
df_cosine = pd.DataFrame({
    'model': ['GPT2', 'Gemini']
})
df_cosine['zero']=0
df_cosine['single']=0
df_cosine['multi']=0
df_cosine['role']=0
df_cosine

In [ ]:
df_model_test = pd.DataFrame({
    'model': ['GPT2', 'Gemini']
})
df_model_test['zero']=0
df_model_test['single']=0
df_model_test['multi']=0
df_model_test['role']=0
df_model_test

In [ ]:
df_grammar = pd.DataFrame({
    'model': ['GPT2', 'Gemini']
})
df_grammar['zero']=0
df_grammar['single']=0
df_grammar['multi']=0
df_grammar['role']=0
df_grammar

In [ ]:
import torch
from transformers import AutoTokenizer
from PIL import Image
import requests
from torchvision import transforms
import torchinfo
text_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
MAX_LEN = 512

In [ ]:
import classes_for_multimodal_bias_classification as cfmbc

In [ ]:
import importlib
import classes_for_multimodal_bias_classification as cfmbc
importlib.reload(cfmbc)

In [ ]:
dict=torch.load("BABE_fine_tuned_model.pt")
model_BABE = cfmbc.BertClass()
model_BABE.load_state_dict(dict)
model_BABE.eval()

In [ ]:
dict=torch.load("fine_tuned_model_nbs.pt")
model_NBS = cfmbc.load_model(drop_proj=0.4379701456194545,drop_fus=0.0888537222443544)
model_NBS.load_state_dict(dict)
model_NBS.eval()

In [ ]:
Ensem_Mod = cfmbc.EnsembleModel_for_single_pred(
    model_text_only=model_BABE,
    model_txt_and_img=model_NBS,
    valid_for_text=cfmbc.valid_BABE,
    valid_for_imgandtxt=cfmbc.valid_NBS,
    valid_loader_txt=cfmbc.valid_ldr_for_babe,
    valid_loader_textAndImage=cfmbc.valid_dataloader_nbs
)

checkpoint = torch.load("ensemble_model.pth")
Ensem_Mod.load_state_dict(checkpoint["model_state_dict"])
Ensem_Mod.eval()

In [ ]:
#https://pytorch.org/docs/stable/nn.functional.html#cosine-similarity
import torch.nn.functional as F

def cosine_similarity_texts(text1, text2, model_name: str = "bert-base-uncased"):

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name)
    model.eval()

    inputs1 = tokenizer(text1, return_tensors="pt", truncation=True, padding=True)
    inputs2 = tokenizer(text2, return_tensors="pt", truncation=True, padding=True)

    with torch.no_grad():
        emb1 = model(**inputs1).last_hidden_state[:, 0, :]  
        emb2 = model(**inputs2).last_hidden_state[:, 0, :]

    cos_sim = F.cosine_similarity(emb1, emb2).item()
    return cos_sim

In [ ]:
df_cosine

In [ ]:
!pip install language_tool_python

In [ ]:
def DataO(article_text, image_path=None):
    df = pd.DataFrame({
        "article": [article_text],
        "text": [article_text],
        "label_bias": [0]
    })
    if image_path:
        df["image_path"] = [image_path]
    return df

In [ ]:
from transformers import AutoTokenizer

text_tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

In [ ]:
import language_tool_python
tool = language_tool_python.LanguageTool('en-US', remote_server='http://localhost:8081')

#Terminal - languagetool-server

In [216]:
#https://languagetool.org/http-api/swagger-ui/#!/default/post_check

prompt_types = ["zero", "single", "multi", "role"]

for i in df_cosine['model']:
    for j in prompt_types:
        if i == 'GPT2':
            org = article
            debiased=run_gpt2(j)
            er = tool.check(debiased)
            er_count = len(er)
            scor=cosine_similarity_texts(org,debiased)
            df_cosine.loc[df_cosine['model'] == 'GPT2', j] =scor
            df_grammar.loc[df_cosine['model'] == 'GPT2', j] =er_count
            df_input = DataO(debiased, image_path=None)
            variab = Ensem_Mod.predict(df_input,input_img_and_txt=None)
            if variab == 1:
                df_model_test.loc[df_cosine['model'] == 'GPT2', j] ='Biased'
            else:
                df_model_test.loc[df_cosine['model'] == 'GPT2', j] = 'Non-Biased'
            

        else:
            org = article
            debiased=gemini_lm(j)
            er = tool.check(debiased)
            er_count = len(er)
            scor=cosine_similarity_texts(org,debiased)
            scor=cosine_similarity_texts(org,debiased)
            df_cosine.loc[df_cosine['model'] == 'Gemini', j] =scor
            df_grammar.loc[df_cosine['model'] == 'Gemini', j] =er_count
            df_input = DataO(debiased, image_path=None)
            if variab == 1:
                df_model_test.loc[df_cosine['model'] == 'Gemini', j] ='Biased'
            else:
                df_model_test.loc[df_cosine['model'] == 'Gemini', j] = 'Non-Biased'

/var/folders/m5/k9gs9x6n0v98jdqp3pn5nc5w0000gn/T/ipykernel_1715/1140033033.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.6705861687660217' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cosine.loc[df_cosine['model'] == 'GPT2', j] =scor
1it [00:00, 10.03it/s]
/var/folders/m5/k9gs9x6n0v98jdqp3pn5nc5w0000gn/T/ipykernel_1715/1140033033.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Non-Biased' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_model_test.loc[df_cosine['model'] == 'GPT2', j] = 'Non-Biased'
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

‘People feel very betrayed’: the British Palestinian out to unseat Labour’s Wes Streeting in Ilford - The Guardian

/var/folders/m5/k9gs9x6n0v98jdqp3pn5nc5w0000gn/T/ipykernel_1715/1140033033.py:13: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.5383835434913635' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_cosine.loc[df_cosine['model'] == 'GPT2', j] =scor
1it [00:00, 11.81it/s]
/var/folders/m5/k9gs9x6n0v98jdqp3pn5nc5w0000gn/T/ipykernel_1715/1140033033.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Non-Biased' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_model_test.loc[df_cosine['model'] == 'GPT2', j] = 'Non-Biased'

‘People feel very betrayed’: the British Palestinian out to unseat Labour’s Wes Streeting in Ilford - The Guardian
‘People feel very betrayed’: the British Palestinian out to unseat Labour’s Wes Streeting in Ilford - The Guardian
‘People feel very betrayed’: the British Palestinian out to unseat Labour’s Wes Streeting in Ilford - The Guardian
‘People feel very betrayed’: the British Palestinian out to unseat Labour’s Wes Streeting in Ilford - The Guardian

In [217]:
df_cosine

    model      zero    single     multi      role
0    GPT2  0.516571  0.299928  0.670586  0.538384
1  Gemini  0.804740  0.592923  0.782821  0.695526

In [218]:
df_model_test

    model        zero      single       multi        role
0    GPT2  Non-Biased  Non-Biased  Non-Biased  Non-Biased
1  Gemini  Non-Biased  Non-Biased  Non-Biased  Non-Biased

In [219]:
df_grammar

    model  zero  single  multi  role
0    GPT2    31     114      7    41
1  Gemini     3       9      2     2